# Generated by Django 5.1.1 on 2025-02-24 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventpurchase',
            name='bukti_pembayaran',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/'),
        ),
        migrations.AddField(
            model_name='eventpurchase',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='eventpurchase',
            name='status_pembelian',
            field=models.CharField(choices=[('pending', 'Pending'), ('verifikasi', 'Menunggu Verifikasi'), ('berhasil', 'Berhasil'), ('gagal', 'Gagal')], max_length=10),
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
