# Generated by Django 5.1.1 on 2025-02-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tiket_created_at_alter_event_tanggal_kegiatan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpurchase',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='eventpurchase',
            name='jumlah_tiket',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
