# Generated by Django 5.1.5 on 2025-02-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tiket_created_at_alter_event_tanggal_kegiatan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpurchase',
            name='jumlah_tiket',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
