# Generated by Django 5.1.5 on 2025-02-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_eventpurchase_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiket',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tiket',
            name='stock',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
