# Generated by Django 5.1.5 on 2025-02-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiket',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
