# Generated by Django 5.1.1 on 2025-03-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_tiket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiket',
            name='big_event',
            field=models.BooleanField(default=False),
        ),
    ]
