# Generated by Django 5.1.5 on 2025-03-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tiket_big_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiket',
            name='big_event',
        ),
        migrations.AddField(
            model_name='event',
            name='big_event',
            field=models.BooleanField(default=False),
        ),
    ]
